name: Update Profile Widgets

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme Widgets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Example step to pull latest blog posts if a blog exists.
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-POST-LIST"
          feed_list: "https://medium.com/feed/@surajmmore" # Placeholder
          commit_message: "Updated blog posts via GitHub Actions"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
